
-- ITEM #1:	HOW TO CREATE NEW DATABASE INSIDE THE SERVER ?		CONSTRUCT A ROOM 
CREATE DATABASE ProductDatabase


-- ITEM #2:	HOW TO CONNECT TO ABOVE DATABASE ?					ENTER THE ROOM 
USE ProductDatabase


-- ITEM #3:	HOW TO CREATE NEW TABLE INSIDE THE DATABASE ?		CONSTRUCT A CUPBOARD WITH SHELVES 
CREATE TABLE tblProducts
(
ProductID  integer,			-- THIS COLUMN STORES DIGITS (EX: 99, -9, 0, 8888 ..)
ProductName character(30)	-- THIS COLUMN STORES UPTO 30 DIGITS, SYMBOLS, ALPHABETS
)

-- ITEM #4:	HOW TO STORE OR INSERT DATA INTO ABOVE TABLE?
-- RULE: SINGLE QUOTES ARE MANDATORY FOR ALPHABETS, SYMBOLS. OPTIONAL FOR DIGITS. 
INSERT INTO tblProducts (ProductID, ProductName) VALUES (1001, 'CAPS')
INSERT INTO tblProducts VALUES (1002, 'CHAINS')
INSERT tblProducts VALUES (1003, 'GLOVES'); 

-- ITEM #5: HOW TO REPORT / VERIFY THE CONTENT FROM ABOVE TABLE?
SELECT ProductID, ProductName FROM tblProducts
SELECT * FROM tblProducts		-- * MEANS TO REPORT ALL COLUMNS

INSERT tblProducts VALUES (1,1)